config/routes.rb
Rails.application.routes.draw do
  root to: 'pictures#new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy]
  resources :pictures do
    collection do
      post :confirm
      get :bookmarks
    end
  end
  resources :users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
  end
  resources :pictures, expect: [:index] do
    resource :favorites, only: [:create, :destroy]
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
  validates_uniqueness_of :picture_id, scope: :user_id
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :picture,  presence: true
  validates :content, presence: true, length: { maximum: 255 }
  belongs_to :user
  mount_uploader :picture, ImageUploader
  has_many :favorites, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  validates :password, length: { minimum: 6 }
  mount_uploader :image, ImageUploader
  has_secure_password
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:edit, :update, :show, :destroy]
  before_action :ensure_current_user_edit_posted_picture, only: [:edit, :update]


  def index
    @pictures = Picture.all
    @users = User.all
    @favorites = Favorite.all.where(user_id: current_user.id)
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        PictureMailer.contact_mail(@picture).deliver
        redirect_to pictures_path
      else
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"削除しました"
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def bookmarks
    @pictures = current_user.favorites
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:picture, :content, :picture_cache)
  end

  def ensure_current_user_edit_posted_picture
    @picture = Picture.find(params[:id])
    if @current_user.id != @picture.user_id
      flash[:notice]="権限がありません"
      redirect_to pictures_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウト'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :ensure_current_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @pictures = @user.pictures

    favorites = Favorite.where(user_id: current_user.id).pluck(:picture_id)  # ログイン中のユーザーのお気に入りのpost_idカラムを取得
    @favorite_list = Picture.find(favorites)     # postsテーブルから、お気に入り登録済みのレコードを取得
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to new_session_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: '更新しました。'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end

  def ensure_current_user
    if @current_user.id != params[:id].to_i
      flash[:notice]="権限がありません"
      redirect_to new_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<br>
<html>
  <head>
    <title>InstClon2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% @picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="picture_picture">
    <%= form.label :picture %>
    <%= image_tag(@picture.picture.url) if @picture.picture && @picture.picture.url %>
    <%= form.file_field :picture %>
    <%= form.hidden_field :picture_cache %>
  </div>

  <div class="picture_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <%= link_to "戻る", :back %>
<% end %>

app/views/pictures/bookmarks.html.erb
<br>

<h1>お気に入り一覧</h1>

<table>
  <tr>
    <th>内容</th>
    <th>投稿者</th>
  </tr>

  <% if @favorite_list.present? %>
  <p>お気に入り一覧:</p>
  <% @favorite_list.each do |picture| %>
    <p><%= picture.name %></p>
  <% end %>
<% end %>
</table>

<%= link_to "戻る", :back %>

app/views/pictures/confirm.html.erb
<br>

<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :picture_cache %>
  <%= form.hidden_field :content %>

  <p>画像:<%= image_tag(@picture.picture.url) if @picture.picture && @picture.picture.url %></p>
    <%= form.hidden_field :image_cache %>
  <p>文章:<%= @picture.content %></p>
  <%= form.submit "投稿する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<br>

<h1>詳細画面</h1>

<%= render 'form' %>

app/views/pictures/index.html.erb
<header>
  <h1>投稿一覧</h1>
    <div class="col">
      <i class="bi bi-cart-plus"></i>
      <i class="bi bi-facebook"></i>
      <i class="bi bi-hand-thumbs-up"></i>
    </div>
</header>

<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
</head>

<tbody>
  <% @pictures.each do |picture| %>
    <tr>
      <td><%= picture.user.name %></td>
      <td><%= image_tag picture.picture.url if picture.picture.present? %></td>
      <td><%= picture.content %></td>
      <td><%= link_to '詳細を確認する', picture_path(picture.id) %></td>

      <% if current_user.id == picture.user.id %>
        <td><%= link_to "画像を編集する", edit_picture_path(picture.id), data: { confirm: '本当に編集をしてもいいですか？' } %></td>
        <td><%= link_to "削除する", picture_path(picture.id), method: :delete, data: { confirm: '本当に削除をしてもいいですか？' }  %></td>
      <% end %>
    </tr>  
  <% end %>
</tbody>

<%= link_to 'お気に入り一覧', bookmarks_pictures_path %>
<%= link_to '投稿画面へ戻る', new_picture_path %>

app/views/pictures/new.html.erb
<br>

<h1>画像投稿</h1>

<%= render 'form' %>

app/views/pictures/show.html.erb
<h1>詳細画面</h1>

<p>
  <strong>Image:</strong>
  <%= image_tag @picture.picture.url %>
</p>

<p><%= @picture.content %></p>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to '編集する', edit_picture_path(@picture) , data: { confirm: '本当に編集していいですか？' } if @picture.user_id == current_user.id %> 
<%= link_to '一覧に戻る',pictures_path %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>


  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.submit "登録する" %>
<% end %>

<%= link_to "戻る", :back %>

app/views/users/new.html.erb
<head>
  <meta charset="utf-8">
  <h1>Sign up</h1>
</head>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<body>
  <%= form_with(model: @user, local: true) do |f| %>  
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.label :image %>
    <%= f.file_field :image %>

    <%= f.submit "Create my account" %>
  <% end %>
</body>

app/views/users/show.html.erb
<br>

<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<% if @user[:image] %>
  <p>プロフィール画像 <%= image_tag @user.image.url %></p>
<% end %>

<% if @favorite_list.present? %>
  <p>お気に入り一覧:</p>
  <% @favorite_list.each do |picture| %>
    <p><%= picture.name %></p>
  <% end %>
<% end %>

<p><%= link_to "お気に入り画面へ行く", bookmarks_pictures_path(@user.id) %></p>
<p><%= link_to "ユーザー画像を編集する", edit_user_path(@user.id) %></p>
<p><%= link_to "投稿一覧のページへ行く", pictures_path %>